version: '3'

services:
  db:
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: sh -c "gunicorn -w 2 nba_stats.wsgi:application -b 0.0.0.0:8000 --reload"
    volumes:
      - .:/app
      - static:/app/static
    depends_on:
      - db
    stdin_open: true
    tty: true

  frontend:
    volumes:
      - "./nba_fe/public:/web/public"
      - "./nba_fe/src:/web/src"
      - "./nba_fe/package.json:/web/package.json"
    ports:
      - "3000:3000"
    build: ./nba_fe
    command: sh -c "npm start"

  nginx:
    image: nginx:1.13.5
    depends_on:
      - web
    restart: always
    volumes:
      - ./nginx/sites-enabled/django:/etc/nginx/conf.d/default.conf:ro
      - static:/data/web/nba/static
    ports:
      - "80:80"


volumes:
  db-data:
  static:
