# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('conference', models.CharField(choices=[('E', 'East'), ('W', 'West')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pos', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center'), ('G', 'Guard'), ('F', 'Forward'), ('GF', 'Guard-Forward'), ('FC', 'Forward-Center')], max_length=2, null=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='SeasonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('playoffs', models.BooleanField(default=False)),
                ('gp', models.IntegerField(blank=True, null=True)),
                ('mp', models.IntegerField(blank=True, null=True)),
                ('fg', models.IntegerField(blank=True, null=True)),
                ('fga', models.IntegerField(blank=True, null=True)),
                ('ft', models.IntegerField(blank=True, null=True)),
                ('fta', models.IntegerField(blank=True, null=True)),
                ('three_pointers', models.IntegerField(blank=True, null=True)),
                ('threes_attempted', models.IntegerField(blank=True, null=True)),
                ('orb', models.IntegerField(blank=True, null=True)),
                ('drb', models.IntegerField(blank=True, null=True)),
                ('ast', models.IntegerField(blank=True, null=True)),
                ('stl', models.IntegerField(blank=True, null=True)),
                ('blk', models.IntegerField(blank=True, null=True)),
                ('tov', models.IntegerField(blank=True, null=True)),
                ('pf', models.IntegerField(blank=True, null=True)),
                ('pts', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='players.Player')),
            ],
            options={
                'ordering': ('player__last_name', 'player__first_name', 'start'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=30)),
                ('wins', models.IntegerField(blank=True)),
                ('losses', models.IntegerField(blank=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.Division')),
            ],
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='players.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_players', to='players.Team'),
        ),
    ]
