# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height_feet',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height_inches',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='years_pro',
            field=models.IntegerField(null=True),
        ),
    ]
