# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20170820_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
