# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonstats',
            name='team',
        ),
    ]
