# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_remove_seasonstats_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonstats',
            options={'ordering': ('player__last_name', 'player__first_name', 'season_year')},
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='end',
        ),
        migrations.RemoveField(
            model_name='seasonstats',
            name='start',
        ),
        migrations.AddField(
            model_name='seasonstats',
            name='season_year',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
