# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20170825_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pos',
            field=models.CharField(blank=True, choices=[('C', 'Center'), ('G', 'Guard'), ('F', 'Forward'), ('GF', 'Guard-Forward'), ('FG', 'Forward-Guard'), ('FC', 'Forward-Center'), ('CF', 'Center-Forward')], max_length=2, null=True),
        ),
    ]
